apiVersion: v2
name: resume-web
description: A Helm chart for deploying the resume-web application
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/ismaelfont/resume-web
sources:
  - https://github.com/ismaelfont/resume-web
maintainers:
  - name: Ismael Font
keywords:
  - resume
  - landing-page
  - metro
